name: fts_fuzzy_match
concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  cancel-in-progress: true
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 3" # At 08:00 on Wednesday # https://crontab.guru/#0_8_*_*_3
  push:
    branches:
      - main
      - v*.*.x
    tags:
      - v*.*.*
  pull_request:
    types: [opened, synchronize]
    branches:
      - '*'
    paths: ["**/*"]

jobs:
  fuzzy_match:
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.3", "3.4", "head"]
        runs-on: ["ubuntu-latest", "macos-latest", "windows-latest"]
    runs-on: ${{matrix.runs-on}}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          working-directory: fts_fuzzy_match
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true
      - run: bundle exec rake compile test
        working-directory: fts_fuzzy_match
